services:
  db:
    image: postgres:15
    container_name: postgres-container-restaurante
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: fastapi-container-restaurante
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/mydatabase
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: fastapi-container-frontend
    depends_on:
      - api
    ports:
      - "5500:5500"
    command: uvicorn main:app --host 0.0.0.0 --port 5500 --reload
    volumes:
      - ./frontend:/app
    working_dir: /app

volumes:
  pgdata:
